export class DomainInvariantError extends Error {
  constructor(
    readonly code:
      | "TASK_STATE_INVALID"
      | "INPUT_SNAPSHOT_IMMUTABLE"
      | "RESULT_ASSET_IMMUTABLE"
      | "PROVIDER_RESUBMIT_FORBIDDEN"
      | "ACTIVE_TASK_RUN_EXISTS"
      | "IDEMPOTENCY_CONFLICT"
      | "BILLING_RECEIPT_INVALID"
      | "BILLING_USAGE_REQUIRED"
      | "BILLING_USAGE_INVALID"
      | "BILLING_USAGE_MISMATCH"
      | "DOCUMENT_CONVERSION_STATE_INVALID"
      | "DOCUMENT_RESULT_IMMUTABLE"
      | "DOCUMENT_KNOWLEDGE_STATE_INVALID"
      | "DOCUMENT_KNOWLEDGE_RESULT_IMMUTABLE"
      | "CREATIVE_PLAN_STATE_INVALID"
      | "STORYBOARD_SPEC_INVALID"
      | "PRODUCTION_RUN_STATE_INVALID"
      | "PRODUCTION_SEGMENT_STATE_INVALID"
      | "DELIVERY_PLAN_STATE_INVALID"
      | "DELIVERY_PREFLIGHT_BLOCKED"
      | "VOICE_AUTHORIZATION_REQUIRED"
      | "CAPABILITY_NOT_CERTIFIED"
      | "BUDGET_LIMIT_EXCEEDED",
    message: string,
  ) {
    super(message);
    this.name = "DomainInvariantError";
  }
}
